const expData = [
  {
    id: "awp",
    name: "AWP",
    desc: "Emulates Hyperion for maximum safety.",
    lvl: 8,
    price: "$6.99",
    period: "weekly",
    plat: ["windows", "windows"],
    pros: ["Emulates Hyperion for safety", "Has a decompiler", "100% sUNC", "Level 8"],
    neutral: ["Hasn't updated for weeks"],
    cons: [],
    verified: true,
    editor: "voxlis.NET",
    txtColor: "text-red-500",
    accentColor: "from-red-600 to-red-700",
    premium: false,
    pricegray: true,
    hasKeySystem: false,
    free: false,
    info: '## Exploit Performance  \n- Although [AWP.gg](/) is associated with [Krampus](/), it operates reliably. The developers focus on avoiding detection and ban waves by using Hyperion emulation techniques. However, running the official Roblox client can still be inconvenient, as it requires reinstallation, and users may occasionally face bans even when using [AWP.gg](/).\n\n> \n\n## Background Information  \n- There is speculation that [AWP.gg](/) is linked to [Krampus](/), an exploit that abruptly shut down on May 11, 2024, shortly after the release of Hyperion 4.0. The developers abandoned the project without offering any updates or refunds, leaving long-term license holders without support. The shutdown was likely due to the challenges in bypassing the new Hyperion 4.0. Although [Krampus](/) did not distribute malware, they issued a misleading "official explanation," falsely claiming their developers were "raided" and even circulating fabricated images as evidence in their Discord server.\n  \n- After months of inactivity, the [Krampus](/) Discord suddenly began promoting a Robux gambling site. It\'s unclear whether the developers are behind the site or were paid for sponsorship, but it\'s most likely that the Discord server was simply sold off.\n\n\n## Developers Background Information\n- Currently managed by [@merkuri6479](/), [@jbhglj7uj](/), and [@etheriut](/), but no additional information is known about them.\n\n\n \n\n> Sources: [reddit.com/r/robloxhackers](), WeAreDevs.NET',
    href: "https://awp.gg",
    priceHref: "https://bloxproducts.com/?affiliate_key=1270744029168009258#AWP",
    uncbuttonlink: "https://sunc.rubis.app/?scrap=HvuHEiAG9iQJ0BTq&key=CwgWgiTmw4bM6OEGKK5quxUWxBJiHWEz",
    hide: true,
  },
  {
    id: "valex",
    name: "Valex",
    desc: "A executor with tons of features and super stable.",
    lvl: 8,
    price: "$7.00",
    period: "weekly",
    plat: ["windows"],
    pros: ["Has a decompiler", "96% sUNC", "Level 8"],
    neutral: [],
    cons: [],
    premium: false,
    pricegray: true,
    verified: true,
    editor: "voxlis.NET",
    txtColor: "text-purple-500",
    accentColor: "from-purple-600 to-purple-700",
    href: "https://valex.io/",
    priceHref: "https://key-empire.com/roblox#valex",
    uncbuttonlink: "https://sunc.rubis.app/?scrap=hIzddwToHu6eFfNA&key=CHXGJNkEYLw9NFzGyW3Sg7A3DPQSx7ZC",
    hideunc: false,
    info: "### **Exploit Performance**\n\n* [Valex]() is a high-performance internal executor for Roblox built for speed, stability, and advanced execution. It’s fully standalone—just one executable with no setup or config files required. [Valex]() uses a custom injection method unlike any other executor on the market, enabling smoother performance, fewer crashes, and high compatibility. It offers broad feature support, and receives updates faster than most competitors. Every version is optimized to ensure maximum performance and reliability.\n\n\n### **Background Information**\n\n* [Valex]() was originally launched as [Nezur]() in 2023 under [1Cheats](), the team behind well-known Roblox and Fortnite cheats. Originally started as an experiment to improve internal injection, [Valex]() quickly gained attention for its low detection rate, solid performance, and reliable updates. With its latest release, it introduced a redesigned core and UI, giving users advanced functionality previously limited to high-end paid exploits. Although internal, [Valex]() is simple to use and acts as a one-click solution for both casual and advanced users. It also runs on a fully custom backend with secure authentication, entirely owned and managed by the [Valex]() team.\n\n\n### **Developer Info**\n\n* [Valex]() is developed by a skilled and experienced team with backgrounds in C++, Java, and full-stack development. The project is led by a developer active in the exploit scene since 2019, known for creating several public scripthubs and tools. The team keeps a low profile but consistently delivers fast updates, prioritizes security, and ensures a smooth user experience. Future plans for [Valex]() include deeper internal integration, more per-game tools, and continued efforts to remain fully working.\n\n> Sources: [reddit.com/r/robloxhackers](), Valex Team",
    hasKeySystem: true,
    free: true,
  },
    {
    id: "milkers",
    name: "Milkers",
    desc: "A private undetected executor since 2013.",
    lvl: 8,
    price: "Invite Only",
    plat: ["windows"],
    pros: ["Undetected since 2013", "Has a decompiler", "100% sUNC", "Level 8"],
    neutral: [],
    cons: [],
    verified: true,
    editor: "voxlis.NET",
    txtColor: "text-green-500",
    accentColor: "from-green-600 to-green-700",
    info: "## Exploit Performance\n\n* [Milkers]() is highly stable and polished, with performance reminiscent of the original [Synapse X](). It rarely crashes, executes scripts reliably, and features a clean white UI. Not much else to criticize—simple and effective.\n\n## Background Information\n\n* [Milkers]() was originally launched on **October 11, 2013**, by [@GuardianAngel]() as a cheat for [Counter-Strike: Global Offensive](). It started as a legit-only tool, with no intention of going public or being sold. Eventually, rage features were added after the tool proved to be undetected. Though those features were easily detected in matchmaking, the cheat itself remained undetected by anti-cheat systems.\n\n* In **2016**, development stopped but resumed in **2018** when [CS\\:GO]() went free-to-play. [@GuardianAngel]() shared the `.dll` files privately with friends, who later pushed him to release it publicly. A website was created and invites were issued, but users who refused to share their invites had their accounts locked—cutting the userbase nearly in half.\n\n* In **2023**, with the announcement of [Counter-Strike 2](), [@GuardianAngel]() shifted focus to [Roblox]() after discovering its new anti-cheat system. The initial Roblox build was unstable, but after heavy trial and error, a solid version was completed in **late 2024**. Licenses were given to trusted users, and development on both Roblox and CS2 versions continued with help from new developers.\n\n* In **2025**, [Milkers']() domain was suspended. During this downtime, operations continued via a [Discord]() server controlled by a custom bot. After the server was eventually terminated, the website was brought back online and development resumed as normal.\n\n## Developers Background Information\n\n* Currently maintained by [@GuardianAngel](). He is known for locking accounts of users who didn't distribute invites and for maintaining a tight grip on distribution.\n\n> Sources: [reddit.com/r/robloxhackers](), Owner of Milkers itself\n",
    premium: false,
    href: "https://milkers.best",
    priceHref: "https://milkers.best",
    hide: true,
    pricegray: true,
  },
    {
    id: "CSVM",
    name: "Luau//CVSM",
    desc: "An ingame script executor.",
    lvl: 2,
    price: "FREE",
    plat: ["windows", "macos", "android", "ios"],
    pros: ["81% sUNC V1"],
    neutral: ["Is a module for one game", "Level 2"],
    cons: [],
    verified: true,
    editor: "voxlis.NET",
    txtColor: "text-blue-500",
    accentColor: "from-blue-600 to-blue-700",
    info: "## Exploit Performance  \n- [LUAU//CVSM]() is a module designed for a game that enables script building in a simulated exploit environment.  \n- It scores [75% UNC]() and [71% sUNC](), reflecting moderate compatibility with most scripts.  \n- Uses [Fiu]() and [LuauCeption]() to interpret scripts in real time.\n\n## Background Information  \n- Developed by [@GelatekForever]() / [@xyzkade](), [@Razonili](), with contributions from [@emperrr]() and [@TimedMarch]().  \n- The only non-native component is the drawing library by [quivings](), which has been properly credited and is planned to be replaced by an in-house version.\n\n## Developer Notes  \n- Some functions are faked or partially simulated. Native-level support exists for things like [hookfunction]() and parts of the [debug]() library via [LBI]().  \n- Features like [cloneref]() return placeholder userdata. Full simulation isn't prioritized unless tied to in-game anticheat mechanisms, as full fidelity would defeat the sandboxed design goals.\n\n> Sources: LUAU//CVSM\n",
    premium: false,
    href: "https://nevelose.xyz/csvm",
    priceHref: "https://yap.com/",
    hide: true,
  },
    {
    id: "ronix",
    name: "Ronix™",
    desc: "A new exploit with high UNC percentage.",
    lvl: 8,
    price: "$4.99",
    period: "lifetime",
    plat: ["windows", "android", "ios"],
    pros: ["2 day long keys", "99% UNC", "Level 8"],
    neutral: ["Includes a Key System"],
    cons: [],
    verified: false,
    editor: "voxlis.NET",
    txtColor: "text-red-500",
    accentColor: "from-red-600 to-red-700",
    href: "https://ronix.club",
    priceHref: "https://ronix.club",
    info: "## Exploit Performance  \n- [Ronix Android](/) and [Ronix Mac](/) are the two primary executors in the Ronix lineup. Both are actively maintained and offer fast, stable performance across supported platforms. [Ronix Android](/) is packaged as a clean `.apk` file, while [Ronix Mac](/) uses a lightweight `.sh` installer — no bloated `.zip` archives or complex configurations. Both prioritize speed, stability, and simple script execution without unnecessary extras.  \n\n## Background Information  \n- [Ronix](/) was created on December 18, 2024, following the deletion of the original [Nexam](/) server. While some believed [Nexam](/) was terminated, it was actually manually deleted for safety. Before this, the [Ronix](/) founder was targeted by the exploit community, facing death threats, Nazi-themed harassment, and personal leaks including IP addresses and real-life photos.  \n- After stepping away from the scene, the founder briefly joined [Latte](/) to escape the harassment. Ultimately, [Ronix](/) was founded as a new, safer continuation of [Nexam](/), rebranding many of its original scripts to keep development going and enable faster updates.  \n\n## Developers Background Information  \n- [@Bdokkx](/) handled key scripts like Fisch and Bloxfruits. [@Noppedout](/) developed the [Ronix Android](/) executor from scratch. [@rangeronver](/), the founder of both [Nexam](/) and [Ronix](/), persisted through extensive community-wide harassment.  \n\n> Sources: [Ronix Development Team](), internal logs, and firsthand accounts\n",
    hide: true,
    hasKeySystem: true,
    free: true,
    pricegray: true,
    warning: true,
    warningInfo:
      "Previously known as Nexam, Ronix has multiple community warnings for threats, doxxing attempts, and targeting projects like Pulsery.net. For more information, please refer to the 'MORE INFO' section if available. Would you still like to proceed to Ronix?",
  },
    {
    id: "celery",
    name: "Celery",
    desc: "A specialized exploit for iOS devices.",
    lvl: 8,
    price: "FREE",
    plat: ["windows"],
    pros: ["100% UNC~", "Level 8"],
    neutral: ["Updates might get delayed"],
    cons: [],
    verified: false,
    editor: "voxlis.NET",
    txtColor: "text-green-500",
    accentColor: "from-green-600 to-green-700",
    href: "https://celery.zip/",
    priceHref: "https://yap.com/",
    info: "## Oops! 🤭\n- Looks like we had not gathered the information yet on this Exploit! This could take some time to finish...\n\nIf you would like to help us out, visit https://github.com/localscripts/voxlis.NET/blob/main/README.md!",
    hide: true,
    hasKeySystem: false,
    free: false,
  },
  {
    id: "jjsploit",
    name: "JJSploit",
    desc: "A basic exploit with no key system.",
    lvl: 3,
    price: "FREE",
    plat: ["windows"],
    pros: ["No keysystem", "40% sUNC~"],
    neutral: ["Level 3", "Xeno - rebranded"],
    cons: [],
    verified: true,
    editor: "voxlis.NET",
    txtColor: "text-blue-500",
    accentColor: "from-blue-600 to-blue-700",
    href: "https://wearedevs.net/d/JJSploit",
    priceHref: "https://yap.com/",
    info: "## Oops! 🤭\n- Looks like we had not gathered the information yet on this Exploit! This could take some time to finish...\n\nIf you would like to help us out, visit https://github.com/localscripts/voxlis.NET/blob/main/README.md!",
    hide: true,
    hasKeySystem: false,
    free: true,
  },
    {
    id: "drift",
    name: "Drift",
    desc: "A free Level 8 executor.",
    lvl: 8,
    price: "FREE",
    plat: [],
    pros: ["Has a decompiler", "98% sUNC", "Level 8"],
    neutral: ["Has a keysystem"],
    cons: [],
    info: '## Exploit Performance\n- [Drift](/) offers a smooth experience and is bundled into a single `.exe` file, unlike many other exploits that come in `.zip` archives with multiple `.dll` files.\n\n## Background Information\n- [Drift](/) was formerly known as [Zorara](/), which launched in July 2024. The rebrand to Drift officially took place on May 16, 2025. Originally based on [Xeno](/), the executor was later rebuilt from the ground up. The project has consistently been maintained by the same developer, [@kq](/). [@kq](/) also previously owned a server called [Trident](/), an unofficial continuation of "[Element]()" showcasing safe exploits. Trident eventually shut down after competitors recruited the entire team.\n\n## Developer Background Information\n- There is little public information about the owner, [@kq](/), aside from their role as Lead Developer of [Drift](/). They are responsible for maintaining the project and developing its transition from a Xeno-based core to a fully custom base.\n\n> Sources: [reddit.com/r/robloxhackers](), Drift Executor Developer Team\n',
    verified: true,
    editor: "voxlis.NET",
    txtColor: "text-red-500",
    accentColor: "from-red-600 to-red-700",
    premium: false,
    href: "https://wearedevs.net/d/Drift",
    priceHref: "",
    uncbuttonlink: "https://sunc.rubis.app/?scrap=JSxQ34jzoGih0I0H&key=Ur05SQl3jlZvjGyEBPLm7ByYVHMV1NFA",
    hide: true,
    hasKeySystem: true,
  },
    {
    id: "autumn",
    name: "Autumn",
    desc: "An exploit with a lifetime license.",
    lvl: 8,
    price: "$7.00",
    period: "lifetime",
    plat: ["windows"],
    pros: ["Has a decompiler", "100% sUNC", "Level 8"],
    neutral: [],
    cons: [],
    verified: false,
    editor: "voxlis.NET",
    txtColor: "text-yellow-500",
    accentColor: "from-yellow-600 to-yellow-700",
    info: "## Exploit Performance  \n- [Autumn]() offers a smooth experience and is bundled into a single `.exe` file, unlike many other exploits that come in `.zip` archives with multiple `.dll` files.\n\n## Background Information  \n- [Autumn](/) officially launched in June 7th 2025, created by a dedicated team of three developers: [@prlx](/), [@visor](/) and [@noir vod](/).\n\n## Developers Background Information  \n- [Autumn]() has no background information.\n\n> Sources: [reddit.com/r/robloxhackers](), Autumn Developers",
    premium: false,
    href: "https://discord.gg/mmTGebPYnm",
    priceHref: "https://robloxcheatz.com/affiliate/voxlisnet",
    uncbuttonlink: "https://r.sunc.su/JgXWs9CVfx",
    hide: true,
    warning: true,
    warningInfo:
      "voxlis.NET has flagged this executor as potentially suspicious and does not recommend its use. Do you still want to proceed to the executor?",
    pricegray: true,
  },
    {
    id: "fatal",
    name: "Fatal",
    desc: "A ratted Level 8 executor.",
    lvl: 8,
    price: "FREE",
    plat: ["Windows"],
    pros: [],
    neutral: [],
    cons: ["Exit scammed 10k-35k$+", "Managed by fat russians", "Ratted users in 2026", "Velocity API paste"],
    verified: false,
    editor: "voxlis.NET",
    txtColor: "text-yellow-500",
    accentColor: "from-yellow-600 to-yellow-700",
    premium: false,
    href: "https://www.reddit.com/r/robloxhackers/comments/1lnp8p3/is_fatal_legitsafe/",
    href: "https://fatal.best",
    priceHref: "",
    hide: true,
    hasKeySystem: false,
    uncbuttonlink: "https://www.reddit.com/r/robloxhackers/comments/1lnp8p3/is_fatal_legitsafe/",
    uncbuttonlink: "https://fatal.best",
    warning: true,
    info: "## Background information\n- Absolute degen in the community, here is a screenshot of him talking to his 'fans':\n\n![alt ](/assets/fatal.png)",
    warningInfo:
      "⚠️ This executor has exit scammed $10,000–$35,000+ ⚠️ — steer clear of Fatal; it's a rebranded copy of Fatality.win using a fake 'invite-only' scheme to appear exclusive — don't be fooled, and help spread the warning.",
  },
  {
    id: "cloudy",
    name: "Cloudy",
    desc: "A free Level 8 executor",
    lvl: 8,
    price: "FREE",
    plat: ["Windows"],
    pros: ["Has a decompiler", "90% sUNC", "Level 8"],
    neutral: [],
    cons: [],
    verified: false,
    editor: "voxlis.NET",
    txtColor: "text-yellow-500",
    accentColor: "from-yellow-600 to-yellow-700",
    premium: false,
    href: "",
    priceHref: "",
    hide: true,
    hasKeySystem: false,
    uncbuttonlink: "https://sunc.rubis.app/?scrap=AuzuME96xLlkLH86&key=9bIsSz3LzqR4TsoPp91UJauf2NZxqEbb",
    warning: true,
    warningInfo:
      "voxlis.NET recommends checking out “MORE INFO” for ArceusX NEO so you know what you’re getting. Would you like to continue to ArceusX NEO's website anyway?",
  },
    {
    id: "Plutora",
    name: "Plutora",
    desc: "An exploit based of WRD Api.",
    lvl: 3,
    price: "FREE",
    plat: ["windows"],
    pros: ["No keysystem"],
    neutral: ["Multi-Inject support", "Level 8", "47% sUNC", "Xeno - rebranded"],
    cons: [],
    verified: true,
    editor: "voxlis.NET",
    txtColor: "text-blue-500",
    accentColor: "from-blue-600 to-blue-700",
    info: "",
    premium: false,
    hasKeySystem: false,
    href: "https://wearedevs.net/d/Plutora",
    priceHref: "",
    hide: true,
    free: true,
    warning: false,
    warningInfo:
      "voxlis.NET recommends checking out “MORE INFO” for RatWare so you know what you’re getting. Would you like to continue to Rat-Ware's website anyway?",
  },
  {
    id: "ratware",
    name: "Ratware",
    desc: "A popular exploit with many users.",
    lvl: 8,
    price: "FREE",
    plat: ["windows"],
    pros: ["150,000+ Users", "100% UNC", "Level 8"],
    neutral: [],
    cons: ["Not verified by voxlis.NET"],
    verified: false,
    editor: "Mr. Ratter",
    txtColor: "text-blue-500",
    accentColor: "from-blue-600 to-blue-700",
    info: '## Exploit Performance \n- Users have reported that while using [RatWare](/), their mouse randomly moves. [@sens6222](/) explains this happens because Hyperion detects RatWare for a split second, and it\'s supposedly fine. Also, when downloading the loader, it doesn\'t actually download the exploit — it downloads your user data.\n\n## Background Information\n- Formerly known as [Atlantis](/), it was rebranded to [Ratlantis](/), and after being exposed for making a rat with ChatGPT, it was renamed again to [RatWare](/), then got exposed again for leaving an unprotected WebHook named `UserLogs`, with the webhook using a rat as its avatar.\n- After being exposed, [@sens6222](/) made an announcement saying "Fuck incognito pastes" and changed [RatWare\'s](/) WebHook to continue downloading user data, but it was left unprotected again, allowing skids to delete it.\n\n\n\n\n## Developers Background Information\n- The exploit is made by [@sens6222](/), but users sometimes encounter an "Error Ratting User" message due to [@sens6222](/) using ChatGPT and not bothering to edit the script.\n',
    premium: false,
    hasKeySystem: false,
    href: "https://link-hub.net/1319977/ratware",
    priceHref: "",
    hide: true,
    free: true,
    warning: true,
    warningInfo:
      "voxlis.NET recommends checking out “MORE INFO” for RatWare so you know what you’re getting. Would you like to continue to Rat-Ware's website anyway?",
  },
  {
    id: "assembly",
    name: "Assembly",
    desc: "The best value external exploit.",
    external: true,
    price: "$9.99",
    period: "lifetime",
    plat: ["windows"],
    pros: ["Custom LUA enviroment", "Multi-Instance support", "Usermode product"],
    neutral: [],
    cons: [],
    verified: true,
    editor: "voxlis.NET",
    txtColor: "text-yellow-500",
    accentColor: "from-purple-600 to-purple-700",
    info: "## Exploit Performance\n- [Assembly](/) operates similarly to other competitors, but with it's own twist. [Assembly](/) delivers a seamless user experience and is packaged into a single .exe, making it a lot more convenient compared to other alternatives that require extracting a .zip file containing multiple folders and other executables.\n## Background Information\n- [Assembly](/) started out as a small external with little promotion made by [@esnesemag](/) (david), as a small passion project to see how far he could go. Yet, when he started making good progress, [david]() saw his friends really liked it and pressured him into making it a real official product. \n- Since then, [Assembly](/) has been getting rapid growth & attention, receiving a ton of updates. Even though [david]() is balancing school and developing [Assembly](/), he still makes a lot of progress daily. \n- Releasing only months ago, [Assembly](/) has grown insanely high and continues to grow even more into the future.\n## Developer Background\n- [Assembly](/) is developed solely by [david](/), who handles everything about the actual software itself. \n- After [Assembly](/) released, though, [yakazt](/) joined the staff team, and is now the primary manager of [Assembly](/), managing public relations and [Assembly](/)'s [Discord server](https://discord.gg/asmlol).\n\n> Sources: [assembly.lol](https://assembly.lol), Assembly staff\n",
    premium: false,
    href: "https://assembly.lol",
    priceHref: "https://key-empire.com/roblox#assembly",
    hide: true,
    hideunc: true,
    pricegray: true,
  },
  {
    id: "kernel",
    name: "Kernel",
    desc: "Decent choice for ingame script execution.",
    lvl: 2,
    price: "FREE",
    plat: ["windows", "macos", "ios", "android"],
    pros: ["87% sUNC (v1)"],
    neutral: ["Is a module for two games", "Level 2"],
    cons: [],
    verified: true,
    editor: "Realirist",
    txtColor: "text-purple-500",
    accentColor: "from-blue-600 to-blue-700",
    info: '## Exploit Performance  \n- [Kernel](/) functions similarly to the [LuaU // CSVM](/) executor, as it shares the same LuaU VM. The main distinction is that [Kernel](/) is actively maintained, whereas [LuaU // CSVM](/) is probably not gonna get any more updates in the future. [Kernel](/) has fast execution speeds, scoring the "very fast" score on the sUNC test. [Kernel]() is technically [LuaU // CSVM](), so they might perform similarly. \n  \n\n## Background Information  \n- Before [Kernel](/), an executor - [Realirist\'s executor](/) launched in early 2023 and officially released around that same time, as an in-game serverside executor.  \n- On September 23, 2024, [Realirist\'s executor](/) vanished, later becoming the rebrand called [Kernel](/), with clientside and "Mixed" execution, which later became only clientside.\n\n## Developers Background Information\n- There is little background information available about the owner, [@Realirist](/), aside from their primary role in working on the UI for [Krnl Remake](/), an [Arcadia](/) paste. \n- [@Realirist](/) had made a [PowerShell](/) script called [trolo.ps1](/), which could send pop-ups to your computer, and shut it down anytime, which could be considered [RAT](/) behavior, even though it was not harmful.\n\n\n> Source: [@Realirist](/)',
    premium: false,
    href: "https://kernels.space/",
    priceHref: "https://kernels.space/",
    uncbuttonlink: "https://rubis.app/view/?scrap=AdbtZX2pP9CxpyTD",
    hide: true,
  },
  {
    id: "lx63",
    name: "LX63",
    desc: "A level 8 keyless exploit.",
    lvl: 8,
    price: "FREE",
    plat: ["windows"],
    pros: ["Has a decompiler", "No keysystem", "95% sUNC", "Level 8"],
    neutral: [],
    cons: [],
    verified: true,
    editor: "voxlis.NET",
    txtColor: "text-blue-500",
    accentColor: "from-blue-600 to-blue-700",
    info: "",
    premium: false,
    hasKeySystem: false,
    href: "https://lx63.xyz",
    priceHref: "",
    hide: false,
    uncbuttonlink: "https://sunc.rubis.app/?scrap=Cn5a1onS77Opiv8p&key=aDMDoLP6KcKDc8aR04ayqU1K7yjg27LP",
    free: true,
    warning: false,
    warningInfo:
      "voxlis.NET recommends checking out “MORE INFO” for RatWare so you know what you’re getting. Would you like to continue to Rat-Ware's website anyway?",
      hide: true,
  },
]
